// app/layout.js
import { Inter, Roboto_Mono } from "next/font/google";
import "./styles/globals.css";
import { Suspense } from "react";
import ClientWrapper from "./components/ClientWrapper";
import Loading from "./loading"; // Ensure this file exists
import { AuthProvider } from "@/context/AuthContext";

// Add fonts as usual (server-side component)
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata = {
  title: "jumbo.com",
  description: "Generated by create next app",
};

// Keep RootLayout as a server component for metadata
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${mono.variable}`}>
      <body className="antialiased">
        <AuthProvider>
          <ClientWrapper>{children}</ClientWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
