import { Inter, Roboto_Mono } from "next/font/google";
import "./styles/globals.css";
import { Suspense } from "react";
import ClientWrapper from "./components/ClientWrapper";
import Loading from "./loading"; // Ensure this file exists

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const mono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata = {
  title: "Ephantronics Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${mono.variable}`}>
      <body className="antialiased">
          <Suspense fallback={<Loading />}>
            <ClientWrapper>{children}</ClientWrapper>
          </Suspense>
      </body>
    </html>
  );
}
